### PR TITLE
reintroduce swagger compatability

### PR DESCRIPTION
**Pull request by Kulikovpavel**
# Description

Reintroduce swagger functionality that existed in v2.3.5 but was removed in v3.0.0. See [Swagger.kt@2.3.5](https://github.com/bkbnio/kompendium/blob/v2.3.5/kompendium-core/src/main/kotlin/io/bkbn/kompendium/core/routes/Swagger.kt)

Closes # (issue)

[425](https://github.com/bkbnio/kompendium/issues/425)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have updated the CHANGELOG in the `Unreleased` section
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by unredundant** [comment]
7402d430f81ac317112af5ccf8adda13

I get this when I try to load the basic playground example at `localhost:8081/swagger-ui`

**Comment by Kulikovpavel** [comment]
Yes, you are right

It seems that it was in 4.16.0-alpha3, but for some reason it was not included in 4.16.0 and even 4.17.0, which was released yesterday
I will discuss this with the swagger-ui team

**Comment by Kulikovpavel** [comment]
They'll introduce it in next major version, 5.x
https://github.com/swagger-api/swagger-ui/issues/8441

**Comment by unredundant** [comment]
Cya in 2026 🫡

**Comment by Kulikovpavel** [comment]
@unredundant future is here, they've released 5.0.0-alpha.0 version, my PR is working with it
image

**Comment by unredundant** [comment]
Nice! Out of curiosity... is there a way to just get the latest swagger ui version? Would be nice if the default could just be the most recent version, and have users override if they want to change it.

Otherwise, we'll need to keep pushing PRs to bump the default version of the swagger client.

**Comment by Kulikovpavel** [comment]
I think it will work for any latest version without @version addition in html template
So https://unpkg.com/swagger-ui-dist/index.js points to 4.18.1
Let me change PR a bit to support future releases by default, but keep opportunity to provide version

So with `swagger(pageTitle = "Simple API Docs", swaggerVersion="5.0.0-alpha.0")` it will work now, without version - in the bright future after swagger-ui release

**Comment by unredundant** [comment]
Awesome 👍

**Pull request merged**
