### PR TITLE
Updated Schema Generator to behave closer to the kotlinx serializer.

### LINKED ISSUE #290: v3 Field name overrides

### PR DESCRIPTION
**Pull request by Stuart-campbell**
# Description

Updated Schema Generator to behave closer to the kotlinx serializer.

- Add support for @Transient annotation 
- Add support for @SerialName annotation on fields
- Removed unbacked fields from schema as they are not serialized into the json.

## Type of change

Closes #290 

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation 
- [ ] Chore

# How Has This Been Tested?

Unit tests added and tested with complex within a project which uses all changes above.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have updated the CHANGELOG in the `Unreleased` section
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by unredundant** [comment]
This is great, thanks for the PR! I do have a bit of a concern, it's something that I've been struggling with a good approach for.  

At the moment, Kompendium is built to support Gson, Jackson, and Kotlinx serializers, and the test suite in the `core` module actually runs every test against each serializer.  

If we start adding direct coupling too Kotlinx annotations, this sort of starts to break down that cross-serializer compatibility, as to have field renames, for example, a Jackson user would need to import the kotlinx dependency.  

I'm not necessarily opposed to treating Kotlinx as the first class citizen, as I think the odds are pretty good that if you are using Ktor, you will be using the kotlin team's own serializer, but need to think on it a bit more.  

Something I was chewing on is in the next major version of Kompendium, maybe define a `json-schema` module that is serializer agnostic (essentially a bunch of interfaces) and then implement a module on a per-serializer basis (so `json-schema-kotlinx` would work out of the box with kotlinx, and so on).

My meandering aside, could you add tests for each of these to the `core` module as well?  The `KompendiumTest` file would be the best place.  Would like to see them being executed in a full openapi spec, and to give confidence that if we merge this, we at least won't break the other serializers :) even if we do start to favor kotlinx as the preferred approach

**Comment by Stuart-campbell** [comment]
Yeah, I was thinking the exact same that this is not flexible for other serializers, my thought on solving in a way for all serializers would mean injecting in components, which would mean switching a load of things away from statics and setting up DI. So I then thought kotlinx is already a dep so this might be a fine stop gap.

Just looking at the `KompendiumTest` and thinking that kotlinx and the others are no longer going to create the same Open Api Spec if you use kotlinx Annotations 🤔

**Comment by Stuart-campbell** [comment]
Did a bit of an overhaul on the approach. Added `SerializableReader` interface for getting included fields and their names. Then added to the Plugin Config, now you can inject the logic you want to fit the JSON library you are using. 

Added a kotlinx default but just test versions for the other libs and Gson and Jackson are pretty complex so thought it would be best the user sets up the logic they want. Also didn't want to add those deps to the core library.

Set up as opt-in so the only change out the box is ignoring unbacked fields. (which could be made opt-in as well but can't think of a reason anyone would want that)

Anyway have a look, see what you think, (I'm not sold on `SerializableReader` name but couldn't think of something better)

**Comment by Stuart-campbell** [comment]
Made an update this morning renamed `SerializableReader` to `SchemaConfigurator` so it can be the place for any future configuration to the generation process. Also made the Default an open class so you can extend that and just override the parts of configuration you care about. Little overkill for two bits now but should make breaking changes less likely in the future.

**Comment by unredundant** [comment]
awesome! I'll pull this code locally play around with it sometime in the next couple days.  Just wanna get a sense for how it feels in action.  

Really appreciate you putting in all this work :)

**Comment by unredundant** [comment]
I like this :) I think it's a really good solution given the constraints of the library.  

One quick thing... Could you add an example in the `playground` module showing how to use the kotlinx configurator? Will help w/ discovery as I'm using that module as a sort of cookbook module for people to reference common patterns.

**Pull request merged**
